# Generated by Django 4.0.4 on 2022-05-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_posts_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author_id',
        ),
    ]
