# Generated by Django 4.0.4 on 2022-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_posts_options_alter_posts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
