# Generated by Django 4.0.4 on 2022-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_category_comments_posts_author_id_posts_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='category_id',
            field=models.ManyToManyField(to='my_app.category'),
        ),
    ]
