# Generated by Django 4.0.4 on 2022-06-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_posts_category_id_posts_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='category_id',
            new_name='category',
        ),
    ]
