# Generated by Django 4.0.4 on 2022-06-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_rename_text_comments_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
