# Generated by Django 4.0.5 on 2022-06-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='subject',
        ),
    ]
